server:
  port: 8089
spring:
  application:
     name: flashcard-service
  datasource:
    url: jdbc:h2:mem:memdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
#JPA Settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
